package perf;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openjdk.jmh.annotations.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

@State(Scope.Benchmark)
@BenchmarkMode(Mode.Throughput)
@OutputTimeUnit(TimeUnit.SECONDS)
public class LoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Setup(Level.Invocation)
  public void setUp() throws MalformedURLException {

    driver = new ChromeDriver();
            //new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.get("http://localhost:8080/onlinebookstore/");
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("CaptchaDiv")).click();
  }
  @TearDown(Level.Invocation)
  public void tearDown() {
    driver.quit();
  }
  @Benchmark
  @Fork(2)
  public void login() {
    driver.findElement(By.id("userName")).click();
    driver.findElement(By.id("userName")).sendKeys("shashi");
    driver.findElement(By.id("Password")).click();
    driver.findElement(By.id("Password")).sendKeys("shashi");
    driver.findElement(By.id("CaptchaInput")).click();
    driver.findElement(By.id("CaptchaInput")).sendKeys(driver.findElement(By.id("CaptchaDiv")).getText());
    driver.findElement(By.cssSelector(".btn")).click();
  }
}
